"""Add tables

Revision ID: 819f3627da2d
Revises: f432c07ed5ed
Create Date: 2025-06-03 15:32:08.670952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819f3627da2d'
down_revision: Union[str, None] = 'f432c07ed5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_seguido',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('usuarioseguido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioseguido'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('usuario_seguidor',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('usuarioseguidor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioseguidor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_seguidor')
    op.drop_table('usuario_seguido')
    # ### end Alembic commands ###
