"""Add Tables

Revision ID: b8302acae8f0
Revises: 
Create Date: 2025-06-03 10:41:34.499999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8302acae8f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('privado', 'grupo'), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_table('grafica',
    sa.Column('id_grafica', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_grafica')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('contrasena', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.Column('verificacion', sa.Enum('pendiente', 'aprobado', 'rechazado'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('adjunto',
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('imagen', 'video', 'enlace', 'grafico'), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_adjunto')
    )
    op.create_table('chat_mensaje',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id_chat'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('chat_miembro',
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['chat.id_chat'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_chat', 'id_usuario')
    )
    op.create_table('dato_grafica',
    sa.Column('id_dato', sa.Integer(), nullable=False),
    sa.Column('id_grafica', sa.Integer(), nullable=True),
    sa.Column('etiqueta', sa.String(length=100), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('valor', sa.DECIMAL(precision=20, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['id_grafica'], ['grafica.id_grafica'], ),
    sa.PrimaryKeyConstraint('id_dato')
    )
    op.create_table('etiqueta',
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=450), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'inactiva'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_etiqueta')
    )
    op.create_table('foro',
    sa.Column('id_foro', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=450), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'inactivo'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_foro')
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol')
    )
    op.create_table('chat_mensaje_adjunto',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_mensaje'], ['chat_mensaje.id_mensaje'], ),
    sa.PrimaryKeyConstraint('id_mensaje', 'id_adjunto')
    )
    op.create_table('publicacion',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('foro_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('publicada', 'eliminada', 'archivada'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['foro_id'], ['foro.id_foro'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_publicacion')
    )
    op.create_table('comentario',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion.id_publicacion'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    op.create_table('publicacion_adjunto',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_adjunto')
    )
    op.create_table('publicacion_etiqueta',
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('id_etiqueta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_etiqueta'], ['etiqueta.id_etiqueta'], ),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id_publicacion'], ),
    sa.PrimaryKeyConstraint('id_publicacion', 'id_etiqueta')
    )
    op.create_table('comentario_adjunto',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('id_adjunto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_adjunto'], ['adjunto.id_adjunto'], ),
    sa.ForeignKeyConstraint(['id_comentario'], ['comentario.id_comentario'], ),
    sa.PrimaryKeyConstraint('id_comentario', 'id_adjunto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario_adjunto')
    op.drop_table('publicacion_etiqueta')
    op.drop_table('publicacion_adjunto')
    op.drop_table('comentario')
    op.drop_table('publicacion')
    op.drop_table('chat_mensaje_adjunto')
    op.drop_table('usuario_rol')
    op.drop_table('foro')
    op.drop_table('etiqueta')
    op.drop_table('dato_grafica')
    op.drop_table('chat_miembro')
    op.drop_table('chat_mensaje')
    op.drop_table('adjunto')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('grafica')
    op.drop_table('chat')
    # ### end Alembic commands ###
