"""Correcion

Revision ID: ca7b6f10da48
Revises: b8302acae8f0
Create Date: 2025-06-03 11:34:31.520928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca7b6f10da48'
down_revision: Union[str, None] = 'b8302acae8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_seguido',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('usuarioseguido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuarioseguido'], ['usuario.usuarioseguido'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('usuario_seguidor',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('usuarioseguidor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuarioseguidor'], ['usuario.usuarioseguidor'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.drop_constraint('chat_mensaje_ibfk_2', 'chat_mensaje', type_='foreignkey')
    op.drop_column('chat_mensaje', 'id_usuario')
    op.add_column('chat_miembro', sa.Column('id_chatmensaje', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_miembro', 'chat_mensaje', ['id_chatmensaje'], ['id_mensaje'])
    op.add_column('usuario', sa.Column('telefono', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('pais', sa.String(length=50), nullable=True))
    op.add_column('usuario', sa.Column('usuarioseguidor', sa.Integer(), nullable=True))
    op.add_column('usuario', sa.Column('usuarioseguido', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'usuarioseguido')
    op.drop_column('usuario', 'usuarioseguidor')
    op.drop_column('usuario', 'pais')
    op.drop_column('usuario', 'direccion')
    op.drop_column('usuario', 'telefono')
    op.drop_constraint(None, 'chat_miembro', type_='foreignkey')
    op.drop_column('chat_miembro', 'id_chatmensaje')
    op.add_column('chat_mensaje', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_mensaje_ibfk_2', 'chat_mensaje', 'usuario', ['id_usuario'], ['id_usuario'])
    op.drop_table('usuario_seguidor')
    op.drop_table('usuario_seguido')
    # ### end Alembic commands ###
