"""Add Seguidores table

Revision ID: d72a57edd2d8
Revises: 819f3627da2d
Create Date: 2025-06-03 15:35:58.800623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd72a57edd2d8'
down_revision: Union[str, None] = '819f3627da2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('usuario_seguidor', sa.Integer(), nullable=False),
    sa.Column('usuario_seguido', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_seguido'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['usuario_seguidor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('usuario_seguidor', 'usuario_seguido')
    )
    op.drop_table('usuario_seguidor')
    op.drop_table('usuario_seguido')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_seguido',
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuarioseguido', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuarioseguido'], ['usuario.id_usuario'], name='usuario_seguido_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario_seguidor',
    sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('usuarioseguidor', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuarioseguidor'], ['usuario.id_usuario'], name='usuario_seguidor_ibfk_1'),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('seguidores')
    # ### end Alembic commands ###
